name: Next Frontend

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [23.3.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: ./ransomhub

      - name: Install PM2
        run: npm install -g pm2
        working-directory: ./ransomhub

      # - name: Run Tests
      #   run: npm test -- --watchAll=false

      - name: Build Project
        run: npm run build
        working-directory: ./ransomhub

      - name: Stop Existing PM2 Process (if any)
        run: |
          pm2 delete all || echo "No existing PM2 processes to stop."

      - name: Start Project with PM2
        run: pm2 start npm --name "ransomhub-app" -- start
        working-directory: ./ransomhub

      - name: Save PM2 Process List
        run: pm2 save
