name: Next Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        working-directory: /var/www/RansomHub-Frontend/ransomhub

      - name: Build Project
        run: npm run build
        working-directory: /var/www/RansomHub-Frontend/ransomhub

      - name: Stop Existing PM2 Process (if any)
        run: pm2 delete all || echo "No existing PM2 processes to stop."

      - name: Start or Restart Project with PM2
        run: RUNNER_TRACKING_ID="" && pm2 start npm --name "ransomhub-frontend" -- start -- -p 3000
        working-directory: /var/www/RansomHub-Frontend/ransomhub

      - name: Save PM2 Process List
        run: pm2 save
